name: Custom build Box86
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout Box86 Repository"
        uses: actions/checkout@v4

      - name: "Environment preparation"
        run: |
          sudo apt-get update
          sudo apt-get -y install git gcc-arm-linux-gnueabihf cmake make python3

      - name: "Build Box86"
        run: |
          mkdir build
          cd build
          cmake .. \
            -DCMAKE_C_COMPILER=arm-linux-gnueabihf-gcc \
            -DCMAKE_C_FLAGS=-marm \
            -DCMAKE_BUILD_TYPE=RelWithDebInfo \
            -DARM_DYNAREC=ON \
            -DHAVE_TRACE=OFF \
            -DCMAKE_VERBOSE_MAKEFILE=ON
          make -j$(nproc) VERBOSE=1

      - name: "Upload Artifact"
        uses: actions/upload-artifact@v4
        with:
          name: box86-android-armv7
          path: build/box86
